
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qureshi Home
 */
public class bitIntervalCalculator extends javax.swing.JFrame {

    /**
     * Creates new form bitIntervalCalculator
     */
    public bitIntervalCalculator() {
        initComponents();
        this.setDefaultCloseOperation(2);
        ManageTxtEditable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        mpg1Btn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        jcb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        l1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Bit Rate");

        txt1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        mpg1Btn.setBackground(new java.awt.Color(51, 51, 51));
        mpg1Btn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        mpg1Btn.setForeground(new java.awt.Color(255, 153, 0));
        mpg1Btn.setText("Calculate");
        mpg1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpg1BtnActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Yahoo", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 153, 0));
        Title.setText("Bit Interval CAlculator");

        txt3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        l3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Bit Interval");

        jcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bit Interval", "Bit Rate" }));
        jcb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mpg1Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(l3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Title)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mpg1Btn)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpg1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpg1BtnActionPerformed
        float bitInterval=0,bitRate=0;
        try{
            if(!"".equals(txt1.getText()))
            bitRate=Float.parseFloat(txt1.getText());
            else
            bitRate=0;
        }catch(NumberFormatException e){
            NumberError(l1.getText());

        }
        try{
            if(!"".equals(txt3.getText()))
            bitInterval=Float.parseFloat(txt3.getText());
            else
            bitInterval=0;
        }catch(NumberFormatException e){
            NumberError(l3.getText());
        }
        switch(jcb.getSelectedIndex()){
            case 0:{
                bitInterval=1/bitRate;
                txt3.setText(bitInterval+"");
                break;
            }
            case 1:{
                bitRate=1/bitInterval;
                txt1.setText(bitRate+"");
                break;
            }
        }
    }//GEN-LAST:event_mpg1BtnActionPerformed

    private void jcbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbItemStateChanged
        ManageTxtEditable();
        System.out.print("Changed");
    }//GEN-LAST:event_jcbItemStateChanged
  public void NumberError(String a){
         JOptionPane.showMessageDialog (null, a+" Should be in Number \n", "Invalid Information", JOptionPane.ERROR_MESSAGE);
    }
     private void ManageTxtEditable(){
        txt1.setEnabled(true);
        txt3.setEnabled(true);
        switch(jcb.getSelectedIndex()){
                case 0:{
                     txt3.setEnabled(false);
                     txt3.setText("");
                     break;
                }
                case 1:{
                     txt1.setEnabled(false);
                     txt1.setText("");
                     break;
                }
                }
    }
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bitIntervalCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bitIntervalCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bitIntervalCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bitIntervalCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bitIntervalCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcb;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JButton mpg1Btn;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}
