/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qureshi Home
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bitRateCalculatorBTN = new javax.swing.JButton();
        bandwidthCalculatorBTN = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        carBtn1 = new javax.swing.JButton();
        truckBtn1 = new javax.swing.JButton();
        carBtn2 = new javax.swing.JButton();
        carBtn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Any Calculator");

        bitRateCalculatorBTN.setBackground(new java.awt.Color(255, 0, 51));
        bitRateCalculatorBTN.setText("Bit Rate Calculator");
        bitRateCalculatorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitRateCalculatorBTNActionPerformed(evt);
            }
        });

        bandwidthCalculatorBTN.setBackground(new java.awt.Color(0, 204, 204));
        bandwidthCalculatorBTN.setText("Bandwidth Calculator");
        bandwidthCalculatorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandwidthCalculatorBTNActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Yahoo", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 153, 0));
        Title.setText("Data Communication");

        carBtn1.setBackground(new java.awt.Color(255, 153, 0));
        carBtn1.setText("Bit Rate & Bit Interval");
        carBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBtn1ActionPerformed(evt);
            }
        });

        truckBtn1.setBackground(new java.awt.Color(0, 204, 204));
        truckBtn1.setText("Nyquit Bit Rate");
        truckBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truckBtn1ActionPerformed(evt);
            }
        });

        carBtn2.setBackground(new java.awt.Color(255, 0, 51));
        carBtn2.setText("Shannon Channel Capacity");
        carBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBtn2ActionPerformed(evt);
            }
        });

        carBtn3.setBackground(new java.awt.Color(255, 153, 0));
        carBtn3.setText("Attenuation Calculator");
        carBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Title)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bitRateCalculatorBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bandwidthCalculatorBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(truckBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Title)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandwidthCalculatorBTN)
                    .addComponent(truckBtn1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bitRateCalculatorBTN)
                    .addComponent(carBtn2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carBtn1)
                    .addComponent(carBtn3))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bitRateCalculatorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitRateCalculatorBTNActionPerformed
        new bitRateCalculator().setVisible(true);
    }//GEN-LAST:event_bitRateCalculatorBTNActionPerformed

    private void bandwidthCalculatorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandwidthCalculatorBTNActionPerformed
        new bandwidthCalculator().setVisible(true);
    }//GEN-LAST:event_bandwidthCalculatorBTNActionPerformed

    private void carBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBtn1ActionPerformed
       new bitIntervalCalculator().setVisible(true);
    }//GEN-LAST:event_carBtn1ActionPerformed

    private void truckBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truckBtn1ActionPerformed
        new NyquistBitRateCalculator().setVisible(true);
    }//GEN-LAST:event_truckBtn1ActionPerformed

    private void carBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBtn2ActionPerformed
       new ShannonChannelCapacity().setVisible(true);
    }//GEN-LAST:event_carBtn2ActionPerformed

    private void carBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBtn3ActionPerformed
        new AttenuationCalculator().setVisible(true);
    }//GEN-LAST:event_carBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton bandwidthCalculatorBTN;
    private javax.swing.JButton bitRateCalculatorBTN;
    private javax.swing.JButton carBtn1;
    private javax.swing.JButton carBtn2;
    private javax.swing.JButton carBtn3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton truckBtn1;
    // End of variables declaration//GEN-END:variables
}
